name: learn-github-actions

on:
  push:
    branches:
    - main
jobs:
  check-bats-version:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g bats
      - run: bats -v